TEST_SOURCE_BACKEND_PERIODIC_PATH = 'mayan.apps.source_apps.sources.tests.source_backends.SourceBackendTestPeriodic'
TEST_SOURCE_BACKEND_STORAGE_PATH = 'mayan.apps.source_apps.sources.tests.source_backends.SourceBackendTestStorage'
TEST_SOURCE_BACKEND_PATH = 'mayan.apps.source_apps.sources.tests.source_backends.SourceBackendSimple'
TEST_SOURCE_LABEL = 'test source'
TEST_SOURCE_LABEL_EDITED = 'test source edited'
