__title__ = 'Mayan EDMS'
__version__ = '4.6.1'
__build__ = 0x040601
__build_string__ = 'v4.6.1-65-ged23b8b3c9a_Mon Mar 4 12:57:54 2024 -0400'
__django_version__ = '4.2'
__author__ = 'Roberto Rosario'
__author_email__ = 'roberto.rosario@mayan-edms.com'
__description__ = 'Free Open Source Electronic Document Management System'
__license__ = 'GPL 2.0'
__copyright_short__ = '2011 Roberto Rosario'
__copyright__ = '{} {}'.format('Copyright', __copyright_short__)
__website__ = 'https://www.mayan-edms.com'
