__title__ = 'Mayan EDMS'
__version__ = '4.7dev0'
__build__ = 0x040602
__build_string__ = 'v4.5.6-481-g79283b4f715_Sun Mar 10 01:47:11 2024 -0400'
__django_version__ = '4.2'
__author__ = 'Roberto Rosario'
__author_email__ = 'roberto.rosario@mayan-edms.com'
__description__ = 'Free Open Source Electronic Document Management System'
__license__ = 'GPL 2.0'
__copyright_short__ = '2011 Roberto Rosario'
__copyright__ = '{} {}'.format('Copyright', __copyright_short__)
__website__ = 'https://www.mayan-edms.com'
