TEST_CASE_ACTION_NAME_SOURCE_CREATE = 'source-create'

TEST_CASE_INTERFACE_NAME_MODEL = 'model'
TEST_CASE_INTERFACE_NAME_REST_API = 'rest-api'
TEST_CASE_INTERFACE_NAME_VIEW = 'view'

TEST_SOURCE_ACTION_CONFIRM_FALSE_NAME = 'action_test_no_confirm'
TEST_SOURCE_ACTION_CONFIRM_TRUE_NAME = 'action_test_confirm'

TEST_SOURCE_LABEL = 'test source'
TEST_SOURCE_LABEL_EDITED = 'test source edited'
